### ISSUE TITLE
Using MATLAB Online: describe how best to download the git repo

### ISSUE THREAD

**Issue by rsnorris** [mathworks/Sumble#1]
When I went to clone the repo, I tried the using the `matlabdrive` folder

![image](https://user-images.githubusercontent.com/39162415/158250710-a7f4042c-4182-4765-96b9-394cbd21fe91.png)

Trying a second time, I wanted to create a new folder, but it can't be done from _Select a _Folder_.

![image](https://user-images.githubusercontent.com/39162415/158251192-47d57e6b-6721-4b82-8306-eea3dcc207bf.png)

Might be helpful to create the folder first, then clone from a repo.

**Comment by nothans** [comment]
Correct. Create a New Folder first. Then, select the new folder from the Folder location field. I tried it with a new folder called Sumble. Let me know if this helps.

![image](https://user-images.githubusercontent.com/691549/158253227-10c17e1f-7cf5-4a29-b20a-8e73d6bf6699.png)

**Comment by tanyamaymorton** [comment]
In MATLAB Online it looks to be possible to skip the manual creation of a new folder. If you enter /MATLAB Drive/Sumble in the Folder location box, then it automatically creates a folder called Sumble. This seems like the simplest option for novice users, and this is the approach I have taken in the updated instructions. Thanks for raising this!

**Comment by tanyamaymorton** [comment]
Instructions have been improved.
